/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export const EarthAnimated = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/EarthAnimated.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions?.CloudsAction.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Earth"
          geometry={nodes.Earth.geometry}
          material={materials.earth}
          rotation={[0, 0, -0.3]}
          scale={2}
        >
          <mesh
            name="Clouds"
            geometry={nodes.Clouds.geometry}
            material={materials.clouds}
            scale={1.01}
          />
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload("/EarthAnimated.gltf");
